### ISSUE TITLE
OpenID: Could not authenticate against third party

### ISSUE THREAD

**Issue by aleprovencio** [go-vikunja/desktop#12]
Hi!

I can't manage to connect `vikunja-desktop` to my instance behind `authelia`.

I do get correctly redirected to `authelia`'s `URL`, put my credentials, but then get a `Could not authenticate against third party` message on this app's `UI`.

This happens on the `flatpak` and `AUR` versions of `vikunja-desktop`. For the sake of testing, I installed `vikunja-app` on my phone, and could successfully authenticate.

`Authelia` logs show this error:
```
"Access Request failed with error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. The 'redirect_uri' from this request does not match the one from the authorize request." method=POST path=/api/oidc/token remote_ip=172.19.0.7
```

Relevant settings:

authelia:
```yaml

auth:
  local:
    enabled: true
  openid:
    enabled: true
    redirecturl: https://vikunja.{{ domain_name }}/auth/openid/
    providers:
      - name: Authelia
        authurl: https://authelia.{{ domain_name }}
        clientid: vikunja
        clientsecret: '{{ stack_apps_vikunja_openid_clientsecret }}'
```

vikunja:
```yaml
  - id: vikunja
    description: Vikunja
    secret: '{{ stack_proxy_auth_authelia_vikunja_secret }}'
    public: false
    authorization_policy: two_factor
    consent_mode: implicit
    redirect_uris:
      - https://vikunja.{{ domain_name }}/auth/openid/authelia
      - http://127.0.0.1:45735/auth/openid/authelia  # vikunja desktop
    scopes:
      - openid
      - email
      - profile
    userinfo_signing_algorithm: none
```
